# Generated by Django 6.0 on 2026-01-23 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rolename",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Имя роли"
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "modifiedat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время последнего изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль системы",
                "verbose_name_plural": "Роли системы",
                "db_table": "nsroles",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="NSUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "userlogin",
                    models.CharField(
                        help_text="Уникальный логин пользователя",
                        max_length=30,
                        unique=True,
                        verbose_name="Логин",
                    ),
                ),
                (
                    "useremail",
                    models.EmailField(
                        help_text="Уникальный email пользователя",
                        max_length=250,
                        unique=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "userphone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "modifiedat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время последнего изменения"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь системы",
                "verbose_name_plural": "Пользователи системы",
                "db_table": "nsusers",
                "ordering": ["userlogin"],
            },
        ),
    ]
