# Generated by Django 6.0 on 2026-01-23 09:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalResultType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название типа цели"
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "modifiedat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время последнего изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип результата цели",
                "verbose_name_plural": "Типы результатов целей",
                "db_table": "goal_result_type",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GoalType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название типа цели"
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "modifiedat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время последнего изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип цели",
                "verbose_name_plural": "Типы целей",
                "db_table": "goal_type",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GoalsBacklog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "goal_name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Имя цели"
                    ),
                ),
                (
                    "goal_reason",
                    models.CharField(
                        max_length=250, verbose_name="Причина возникновения цели"
                    ),
                ),
                (
                    "visibleforothers",
                    models.BooleanField(
                        default=False,
                        help_text="Цель может закрыта на просмотр остальным участникам сессии",
                        verbose_name="Видимость для других",
                    ),
                ),
                (
                    "priority_weight",
                    models.IntegerField(
                        help_text="Вес цели относительно всех других, уникален для пользователя",
                        verbose_name="Вес цели",
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "modifiedat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время последнего изменения"
                    ),
                ),
                (
                    "goal_result_type",
                    models.ForeignKey(
                        db_column="goal_result_type_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="goals.goalresulttype",
                        verbose_name="Тип результата цели",
                    ),
                ),
                (
                    "nsuser",
                    models.ForeignKey(
                        db_column="nsuser_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "goal_type",
                    models.ForeignKey(
                        db_column="goal_type_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="goals.goaltype",
                        verbose_name="Тип цели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель в бэклоге",
                "verbose_name_plural": "Цели в бэклоге",
                "db_table": "goals_backlog",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nsuser", "priority_weight"),
                        name="unique_user_priority_weight",
                    )
                ],
            },
        ),
    ]
