# Generated by Django 6.0 on 2026-01-23 09:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goals", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NSSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("stop_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "createdat",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "modifiedat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время последнего изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия целеполагания",
                "verbose_name_plural": "Сессии целеполагания",
                "db_table": "nssessions",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SessionStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        verbose_name="Название статуса сессии",
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "modifiedat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время последнего изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус сессии",
                "verbose_name_plural": "Статусы сессий",
                "db_table": "session_status",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SessionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название типа сессии"
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "modifiedat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время последнего изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип сессии",
                "verbose_name_plural": "Типы сессий",
                "db_table": "session_type",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GoalWeightHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("goal_weight", models.IntegerField(verbose_name="Вес цели")),
                (
                    "change_reason",
                    models.CharField(max_length=250, verbose_name="Причина изменения"),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "modifiedat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время последнего изменения"
                    ),
                ),
                (
                    "nssession",
                    models.ForeignKey(
                        db_column="nssession_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="weight_history",
                        to="goal_sessions.nssession",
                        verbose_name="Сессия",
                    ),
                ),
            ],
            options={
                "verbose_name": "История веса цели",
                "verbose_name_plural": "История весов целей",
                "db_table": "goal_weight_history",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SessionGoal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "current_weight",
                    models.IntegerField(
                        help_text="Текущий вес цели в сессии",
                        verbose_name="Текущий вес",
                    ),
                ),
                (
                    "goal_plan",
                    models.CharField(
                        max_length=1024, verbose_name="Краткий план достижения"
                    ),
                ),
                (
                    "goal_steps",
                    models.CharField(
                        max_length=1024, verbose_name="Что сделано для достижения цели"
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "modifiedat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время последнего изменения"
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        db_column="goal_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="goals.goalsbacklog",
                        verbose_name="Цель",
                    ),
                ),
                (
                    "nssession",
                    models.ForeignKey(
                        db_column="nssession_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="session_goals",
                        to="goal_sessions.nssession",
                        verbose_name="Сессия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель в сессии",
                "verbose_name_plural": "Цели в сессии",
                "db_table": "session_goals",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="nssession",
            name="session_status",
            field=models.ForeignKey(
                db_column="session_status_id",
                on_delete=django.db.models.deletion.RESTRICT,
                to="goal_sessions.sessionstatus",
                verbose_name="Статус сессии",
            ),
        ),
        migrations.AddField(
            model_name="nssession",
            name="session_type",
            field=models.ForeignKey(
                db_column="session_type_id",
                on_delete=django.db.models.deletion.RESTRICT,
                to="goal_sessions.sessiontype",
                verbose_name="Тип сессии",
            ),
        ),
        migrations.CreateModel(
            name="SUR",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "modifiedat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время последнего изменения"
                    ),
                ),
                (
                    "nsrole",
                    models.ForeignKey(
                        db_column="nsrole_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="users.nsrole",
                        verbose_name="Роль",
                    ),
                ),
                (
                    "nssession",
                    models.ForeignKey(
                        db_column="nssession_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="participants",
                        to="goal_sessions.nssession",
                        verbose_name="Сессия",
                    ),
                ),
                (
                    "nsuser",
                    models.ForeignKey(
                        db_column="nsuser_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник сессии с ролью",
                "verbose_name_plural": "Участники сессий с ролями",
                "db_table": "sur",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nsuser", "nssession", "nsrole"),
                        name="unique_user_session_role",
                    )
                ],
            },
        ),
    ]
